# Generated by Django 4.0 on 2021-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='modules',
            field=models.ManyToManyField(to='learning.Module'),
        ),
    ]
